Changed to %% as there seems to be a bug
configparser.InterpolationMissingOptionError: Bad value substitution: option 'logging-format' in section 'log-capture' contains an interpolation key 'name' which is not a valid option name. Raw value: '%(name)s: %(levelname)s: %(message)s'