[IIN][FBMN] Method to collapse ion identity networks to single nodes  (#649)
* Update .gitignore

* Added edge keys (EdgeType) for later removal of edges

* Added option to collapse ion networks to graphml export

Logic in ion_network_utils.py
- finds all ion identity nodes
- only keeps node with maximum intensity, merges other ion into this ion node
- redirects all edges to this node
- removes ion identity edges
- adds specific new attributes to collapsed "neutral molecule" nodes

* Started test for ion identity network collapsing

* Update test_workflow_components.py

* Cheap IIN test

* Collapse argument made optional and added default=False

* Added link to new utils python file

* Moved ion_network_utils from shared to FBMN folder

* Added logger utils and symlink

* Added ion network utils to shared_code and symlink

* try logging in test

* try logging in graphml export

* Removed symlinks (tests were not working)

* Added unittest.cfg to test folder

* Added loggings

* Logging does not work

* Changed logging format

* Changed nose2 --config to nose2 -c

* Changed nose2 -c to nose2 -c unittest.cfg

* Config is loaded - changed format again

* Changed to logging format

* Changed to %% as there seems to be a bug

configparser.InterpolationMissingOptionError: Bad value substitution: option 'logging-format' in section 'log-capture' contains an interpolation key 'name' which is not a valid option name. Raw value: '%(name)s: %(levelname)s: %(message)s'

* Failing the iin collapsing test

* clear-handlers false

* always-on false

* Safely compare floating point numbers with numpy.isclose

* Access correct edge in IIMN test

* cannot access Cosine edge - try to print all

* cannot access Cosine edge - try to print all2

* Corrected the FBMN test - was looking for IIN edge

* Corrected the FBMN test - was looking for IIN edge2

* Corrected the FBMN test - was looking for IIN edge2

* Correct case for ION_EDGE_TYPE

* Testing numpy.isclose to compare floats

* All constants to constants.py, e.g. use: CONST.NODE.TYPE_ATTRIBUTE

* Made sub network collapsing more modular with constants.py to access attributes

* Correct constants.NODE attribute for specific ions

* Weird logging string format warning fixed

* New way to collapse a list of nodes into one + all edges of the same type to one edge

* Test add/exchange edge debug

* Remove some debug logs

* changing order of logging imports

* explicitly setting the collapse function

* bump version

* adding new node to execute for outputting graphml collapse via IIN

* renaming consts for network

* fixing command line arguments

* adding linkout for IIN collapsed

* Fixed node type

* MS-DIAL and XCMS camera collapsing support

* Added logging

* Fixed get_ion_net_id

* Added more constants to constants_network.py

* Sort ion identity network nodes by library match score if not then abundance

* Fixed get ion net id calls

* Fixed node sorting

* Fix KeyError

* Fixed sorting attributes as list

* Added default=0 to sort nodes by attribute if value=none

* Convert values to float before sorting

* Actually return after sorting

* Added collapsed list of library matches to collapsed nodes

* intensity to integer to avoid floating point in export

* Removed TODO

* Added equal_adduct check and attribute to nodes

* fixed empty adduct strings

* fixed empty adduct strings after clean

* fixed empty adduct strings after clean2

* Removed int conversion. Cytoscape treats int as string

* Test log feature node type

* Test log feature node type

* Test log feature node type

* Test log feature node type

* remove whitespaces on ion net id

* ion net id to float, remove logging

* changed detected tool to string

* removed logger

* adding test tasks for iin collapse

Co-authored-by: Robin Schmid <rschmid1789@gmail.com>
Co-authored-by: robinschmid <robinschmid@uni-muenster.de>